In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("train.csv")
data_file = pd.read_csv("test.csv")
data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
from sklearn.model_selection import train_test_split
labels = data['label']
col = list(data.columns)
col.remove('label')
data_train,data_test,label_train,label_test = train_test_split(data[col],labels,train_size=0.9)
data_train.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
35847,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1399,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
33985,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37202,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10629,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
print(data['label'].value_counts())
type(data_train)

1    4684
7    4401
3    4351
9    4188
2    4177
6    4137
0    4132
4    4072
8    4063
5    3795
Name: label, dtype: int64

pandas.core.frame.DataFrame

In [6]:
from sklearn.metrics import accuracy_score,f1_score

In [7]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(data_train,label_train)
pred = rf.predict(data_test)
pred

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([6, 6, 2, ..., 6, 3, 9], dtype=int64)

In [8]:
acc = accuracy_score(label_test,pred)
fs = f1_score(label_test,pred,average=None)
print(acc)
fs

0.935952380952381

array([0.97142857, 0.96723164, 0.93348891, 0.91011236, 0.92840647,
       0.92249047, 0.96577017, 0.9478458 , 0.91428571, 0.89440994])

In [ ]:
param_grid = { "criterion" : ["gini", "entropy"], "min_samples_leaf" : [1, 5, 10, 25, 50], "min_samples_split" : [2, 4, 10, 12, 16, 18, 25], "n_estimators": [50,100, 300]}
from sklearn.model_selection import GridSearchCV
rf = RandomForestClassifier(n_estimators=100, max_features='auto', oob_score=True, random_state=1, n_jobs=-1)
clf = GridSearchCV(estimator=rf, param_grid=param_grid, n_jobs=-1)
clf.fit(data[col], data['label'])
clf.best_params_

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)

In [ ]:
rf = RandomForestClassifier(n_estimators =100)
rf.fit(data[col],labels)
pred = rf.predict(data_file)
pd.DataFrame({"ImageId":list(range(1,len(data_file)+1)),"Label":pred}).to_csv("output_svm.csv",index=False)